token=8390091402:AAHNVa8BnZp4Za2v8LbI5VOh6d7ChVjDcWI

onboarding.saudacao=Bem-vindo ao Aurora RH. Como podemos te chamar?

onboarding.dados_cpf=Tudo bem, {nome}? Por favor, me informe o seu CPF.
onboarding.confirma_dados_cpf={nome}, voce confirma o seu cpf {cpf}?

menu_principal={nome}, o que você deseja fazer?
menu_ferias={nome}, qual o tipo de férias que você deseja escolher?

ferias.saudacao={nome}, indique a melhor data para as suas ferias.
ferias.sucesso={nome}, suas férias foram marcadas! Vamos preparar tudo para essa data tão esperada.\n
ferias.erro={nome}, você ainda não completou o tempo necessário. Admissão: {dataAdmissao}, meses: {tempoDecorrido}\n

holerite.sucesso={nome}, esses são seus ultimos holerites:\n{resultado}

empregadoAcao.erro={nome}, não te encontramos em nossa base de dados! Por favor, me informe novamente o seu CPF.\n
holeriteAcao.erro={nome}, ainda não temos holerites em seu nome.\n

encerramento=Obrigado por utilizar o Aurora RH. Nos veremos em breve!
